### ISSUE TITLE
Simple chrome ext to identify forms

### ISSUE THREAD

**Issue by dhowe** [dhowe/BrowserHacking#1]
Identify, then add colored border around form

**Comment by dhowe** [comment]
Now, for each form, grab each 'input' element, and set its value to be its 'name' attribute.
As an example see the first few input fields on the gmail signup page:

![screen shot 2016-05-11 at 8 22 31 pm](https://cloud.githubusercontent.com/assets/737638/15180771/265c5806-17b6-11e6-9513-4aa1f226a188.png)

![screen shot 2016-05-11 at 8 23 24 pm](https://cloud.githubusercontent.com/assets/737638/15180792/4c2d3df2-17b6-11e6-91cc-0c501a5a8fb1.png)

**Comment by CyrusSUEN** [comment]
Put on hold since we switched to existing extension formfiller
https://github.com/husainshabbir/form-filler
